services:
  fastcgi-service:
    image: fastcgi-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
  fastcgi-nginx:
    image: fastcgi-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - type: bind
        source: /run 
        target: /run
    